Map periodicTable = {
  1: {
    'chemical_sign': 'H',
    'name': 'Hidrogén',
    'license_number': 1,
    'relative_mass': 1.008,
  },
  2: {
    'chemical_sign': 'He',
    'name': 'Hélium',
    'license_number': 2,
    'relative_mass': 4.00,
  },
  3: {
    'chemical_sign': 'Li',
    'name': 'Lítium',
    'license_number': 3,
    'relative_mass': 6.94,
  },
  4: {
    'chemical_sign': 'Be',
    'name': 'Berillium',
    'license_number': 4,
    'relative_mass': 9.01,
  },
  5: {
    'chemical_sign': 'B',
    'name': 'Bór',
    'license_number': 5,
    'relative_mass': 10.81,
  },
  6: {
    'chemical_sign': 'C',
    'name': 'Szén',
    'license_number': 6,
    'relative_mass': 12.01,
  },
  7: {
    'chemical_sign': 'N',
    'name': 'Nitrogén',
    'license_number': 7,
    'relative_mass': 14.01,
  },
  8: {
    'chemical_sign': 'O',
    'name': 'Oxigén',
    'license_number': 8,
    'relative_mass': 16.00,
  },
  9: {
    'chemical_sign': 'F',
    'name': 'Flour',
    'license_number': 9,
    'relative_mass': 19.00,
  },
  10: {
    'chemical_sign': 'Ne',
    'name': 'Neon',
    'license_number': 10,
    'relative_mass': 20.18,
  },
  11: {
    'chemical_sign': 'Na',
    'name': 'Nátrium',
    'license_number': 11,
    'relative_mass': 22.99,
  },
  12: {
    'chemical_sign': 'Mg',
    'name': 'Magnézium',
    'license_number': 12,
    'relative_mass': 24.31,
  },
  13: {
    'chemical_sign': 'Al',
    'name': 'Alumínium',
    'license_number': 13,
    'relative_mass': 26.98,
  },
  14: {
    'chemical_sign': 'Si',
    'name': 'Szilícium',
    'license_number': 14,
    'relative_mass': 28.09,
  },
  15: {
    'chemical_sign': 'P',
    'name': 'Foszfor',
    'license_number': 15,
    'relative_mass': 30.97,
  },
  16: {
    'chemical_sign': 'S',
    'name': 'Kén',
    'license_number': 16,
    'relative_mass': 32.06,
  },
  17: {
    'chemical_sign': 'Cl',
    'name': 'Klór',
    'license_number': 17,
    'relative_mass': 35.45,
  },
  18: {
    'chemical_sign': 'Ar',
    'name': 'Argon',
    'license_number': 18,
    'relative_mass': 39.95,
  },
  19: {
    'chemical_sign': 'K',
    'name': 'Kálium',
    'license_number': 19,
    'relative_mass': 39.10,
  },
  20: {
    'chemical_sign': 'Ca',
    'name': 'Kálcium',
    'license_number': 20,
    'relative_mass': 40.08,
  },
  21: {
    'chemical_sign': 'Sc',
    'name': 'Szkandium',
    'license_number': 21,
    'relative_mass': 44.96,
  },
  22: {
    'chemical_sign': 'Ti',
    'name': 'Titán',
    'license_number': 22,
    'relative_mass': 47.90,
  },
  23: {
    'chemical_sign': 'V',
    'name': 'Vanádium',
    'license_number': 23,
    'relative_mass': 50.94,
  },
  24: {
    'chemical_sign': 'Cr',
    'name': 'Króm',
    'license_number': 24,
    'relative_mass': 52.00,
  },
  25: {
    'chemical_sign': 'Mn',
    'name': 'Mangán',
    'license_number': 25,
    'relative_mass': 54.94,
  },
  26: {
    'chemical_sign': 'Fe',
    'name': 'Vas',
    'license_number': 26,
    'relative_mass': 55.85,
  },
  27: {
    'chemical_sign': 'Co',
    'name': 'Kobalt',
    'license_number': 27,
    'relative_mass': 58.93,
  },
  28: {
    'chemical_sign': 'Ni',
    'name': 'Nikkel',
    'license_number': 28,
    'relative_mass': 58.71,
  },
  29: {
    'chemical_sign': 'Cu',
    'name': 'Réz',
    'license_number': 29,
    'relative_mass': 63.54,
  },
  30: {
    'chemical_sign': 'Zn',
    'name': 'Cink',
    'license_number': 30,
    'relative_mass': 65.37,
  },
  31: {
    'chemical_sign': 'Ga',
    'name': 'Gallium',
    'license_number': 31,
    'relative_mass': 69.72,
  },
  32: {
    'chemical_sign': 'Ge',
    'name': 'Germánium',
    'license_number': 32,
    'relative_mass': 72.59,
  },
  33: {
    'chemical_sign': 'As',
    'name': 'Arzén',
    'license_number': 33,
    'relative_mass': 74.92,
  },
  34: {
    'chemical_sign': 'Se',
    'name': 'Szelén',
    'license_number': 34,
    'relative_mass': 78.96,
  },
  35: {
    'chemical_sign': 'Br',
    'name': 'Bróm',
    'license_number': 35,
    'relative_mass': 79.91,
  },
  36: {
    'chemical_sign': 'Kr',
    'name': 'Kripton',
    'license_number': 36,
    'relative_mass': 83.80,
  },
  37: {
    'chemical_sign': 'Rb',
    'name': 'Rubídium',
    'license_number': 37,
    'relative_mass': 85.47,
  },
  38: {
    'chemical_sign': 'Sr',
    'name': 'Stroncium',
    'license_number': 38,
    'relative_mass': 87.62,
  },
  39: {
    'chemical_sign': 'Y',
    'name': 'Ittrium',
    'license_number': 39,
    'relative_mass': 88.91,
  },
  40: {
    'chemical_sign': 'Zr',
    'name': 'Cirkónium',
    'license_number': 40,
    'relative_mass': 91.22,
  },
  41: {
    'chemical_sign': 'Nb',
    'name': 'Nióbium',
    'license_number': 41,
    'relative_mass': 92.91,
  },
  42: {
    'chemical_sign': 'Mo',
    'name': 'Molibdén',
    'license_number': 42,
    'relative_mass': 95.94,
  },
  43: {
    'chemical_sign': 'Te',
    'name': 'Technécium',
    'license_number': 43,
    'relative_mass': 98.0,
  },
  44: {
    'chemical_sign': 'Ru',
    'name': 'Ruténium',
    'license_number': 44,
    'relative_mass': 101.07,
  },
  45: {
    'chemical_sign': 'Rh',
    'name': 'Ródium',
    'license_number': 45,
    'relative_mass': 102.91,
  },
  46: {
    'chemical_sign': 'Pd',
    'name': 'Palládium',
    'license_number': 46,
    'relative_mass': 106.4,
  },
  47: {
    'chemical_sign': 'Ag',
    'name': 'Ezüst',
    'license_number': 47,
    'relative_mass': 107.87,
  },
  48: {
    'chemical_sign': 'Cd',
    'name': 'Kadmium',
    'license_number': 48,
    'relative_mass': 112.40,
  },
  49: {
    'chemical_sign': 'In',
    'name': 'Indium',
    'license_number': 49,
    'relative_mass': 114.82,
  },
  50: {
    'chemical_sign': 'Sn',
    'name': 'Ón',
    'license_number': 50,
    'relative_mass': 118.69,
  },
  51: {
    'chemical_sign': 'Sb',
    'name': 'Antimon',
    'license_number': 51,
    'relative_mass': 121.75,
  },
  52: {
    'chemical_sign': 'Te',
    'name': 'Tellúr',
    'license_number': 52,
    'relative_mass': 127.60,
  },
  53: {
    'chemical_sign': 'I',
    'name': 'Jód',
    'license_number': 53,
    'relative_mass': 126.90,
  },
  54: {
    'chemical_sign': 'Xe',
    'name': 'Xenon',
    'license_number': 54,
    'relative_mass': 131.30,
  },
  55: {
    'chemical_sign': 'Cs',
    'name': 'Cézium',
    'license_number': 55,
    'relative_mass': 132.91,
  },
  56: {
    'chemical_sign': 'Ba',
    'name': 'Bárium',
    'license_number': 56,
    'relative_mass': 137.34,
  },
  57: {
    'chemical_sign': 'La',
    'name': 'Lantán',
    'license_number': 57,
    'relative_mass': 138.91,
  },
  58: {
    'chemical_sign': 'Ce',
    'name': 'Cérium',
    'license_number': 58,
    'relative_mass': 140.12,
  },
  59: {
    'chemical_sign': 'Pr',
    'name': 'Prazeodímium',
    'license_number': 59,
    'relative_mass': 140.91,
  },
  60: {
    'chemical_sign': 'Nd',
    'name': 'Neodímium',
    'license_number': 60,
    'relative_mass': 144.24,
  },
  61: {
    'chemical_sign': 'Rm',
    'name': 'Prométium',
    'license_number': 61,
    'relative_mass': 147.0,
  },
  62: {
    'chemical_sign': 'Sm',
    'name': 'Szamárium',
    'license_number': 62,
    'relative_mass': 150.35,
  },
  63: {
    'chemical_sign': 'Eu',
    'name': 'Európium',
    'license_number': 63,
    'relative_mass': 151.96,
  },
  64: {
    'chemical_sign': 'Gd',
    'name': 'Gadolínium',
    'license_number': 64,
    'relative_mass': 157.25,
  },
  65: {
    'chemical_sign': 'Tb',
    'name': 'Terbium',
    'license_number': 65,
    'relative_mass': 158.92,
  },
  66: {
    'chemical_sign': 'Dy',
    'name': 'Diszprózium',
    'license_number': 66,
    'relative_mass': 162.50,
  },
  67: {
    'chemical_sign': 'Ho',
    'name': 'Holmium',
    'license_number': 67,
    'relative_mass': 164.93,
  },
  68: {
    'chemical_sign': 'Er',
    'name': 'Erbrium',
    'license_number': 68,
    'relative_mass': 167.26,
  },
  69: {
    'chemical_sign': 'Tm',
    'name': 'Túlium',
    'license_number': 69,
    'relative_mass': 168.93,
  },
  70: {
    'chemical_sign': 'Yb',
    'name': 'Itterbium',
    'license_number': 70,
    'relative_mass': 173.04,
  },
  71: {
    'chemical_sign': 'Lu',
    'name': 'Lutécium',
    'license_number': 71,
    'relative_mass': 174.97,
  },
  72: {
    'chemical_sign': 'Hf',
    'name': 'Hafnium',
    'license_number': 72,
    'relative_mass': 178.49,
  },
  73: {
    'chemical_sign': 'Ta',
    'name': 'Tantál',
    'license_number': 73,
    'relative_mass': 180.95,
  },
  74: {
    'chemical_sign': 'W',
    'name': 'Volfrám',
    'license_number': 74,
    'relative_mass': 183.85,
  },
  75: {
    'chemical_sign': 'Re',
    'name': 'Rénium',
    'license_number': 75,
    'relative_mass': 186.2,
  },
  76: {
    'chemical_sign': 'Os',
    'name': 'Ozmium',
    'license_number': 76,
    'relative_mass': 190.2,
  },
  77: {
    'chemical_sign': 'Ir',
    'name': 'Iridium',
    'license_number': 77,
    'relative_mass': 192.2,
  },
  78: {
    'chemical_sign': 'Pt',
    'name': 'Platina',
    'license_number': 78,
    'relative_mass': 195.09,
  },
  79: {
    'chemical_sign': 'Au',
    'name': 'Arany',
    'license_number': 79,
    'relative_mass': 196.97,
  },
  80: {
    'chemical_sign': 'Hg',
    'name': 'Higany',
    'license_number': 80,
    'relative_mass': 200.59,
  },
  81: {
    'chemical_sign': 'Tl',
    'name': 'Tallium',
    'license_number': 81,
    'relative_mass': 204.37,
  },
  82: {
    'chemical_sign': 'Pb',
    'name': 'Ólom',
    'license_number': 82,
    'relative_mass': 207.19,
  },
  83: {
    'chemical_sign': 'Bi',
    'name': 'Bizmut',
    'license_number': 83,
    'relative_mass': 208.98,
  },
  84: {
    'chemical_sign': 'Po',
    'name': 'Polónium',
    'license_number': 84,
    'relative_mass': 210.0,
  },
  85: {
    'chemical_sign': 'At',
    'name': 'Asztáncium',
    'license_number': 85,
    'relative_mass': 210.0,
  },
  86: {
    'chemical_sign': 'Rn',
    'name': 'Radon',
    'license_number': 86,
    'relative_mass': 222.0,
  },
  87: {
    'chemical_sign': 'Fr',
    'name': 'Francium',
    'license_number': 87,
    'relative_mass': 223.0,
  },
  88: {
    'chemical_sign': 'Ra',
    'name': 'Rádium',
    'license_number': 88,
    'relative_mass': 226.0,
  },
  89: {
    'chemical_sign': 'Ac',
    'name': 'Aktínium',
    'license_number': 89,
    'relative_mass': 227.0,
  },
  90: {
    'chemical_sign': 'Th',
    'name': 'Tórium',
    'license_number': 90,
    'relative_mass': 232.0,
  },
  91: {
    'chemical_sign': 'Pa',
    'name': 'Proaktínium',
    'license_number': 91,
    'relative_mass': 231.0,
  },
  92: {
    'chemical_sign': 'U',
    'name': 'Urán',
    'license_number': 92,
    'relative_mass': 238.03,
  },
  93: {
    'chemical_sign': 'Np',
    'name': 'Neptúnium',
    'license_number': 93,
    'relative_mass': 237.0,
  },
  94: {
    'chemical_sign': 'Pu',
    'name': 'Plutónium',
    'license_number': 94,
    'relative_mass': 240.0,
  },
  95: {
    'chemical_sign': 'Am',
    'name': 'Amerícium',
    'license_number': 95,
    'relative_mass': 243.0,
  },
  96: {
    'chemical_sign': 'Cm',
    'name': 'Kűrium',
    'license_number': 96,
    'relative_mass': 247.0,
  },
  97: {
    'chemical_sign': 'Bk',
    'name': 'Berkélium',
    'license_number': 97,
    'relative_mass': 247.0,
  },
  98: {
    'chemical_sign': 'Cf',
    'name': 'Kalifornium',
    'license_number': 98,
    'relative_mass': 249.0,
  },
  99: {
    'chemical_sign': 'Es',
    'name': 'Einsteinium',
    'license_number': 99,
    'relative_mass': 254.0,
  },
  100: {
    'chemical_sign': 'Fm',
    'name': 'Ferimium',
    'license_number': 100,
    'relative_mass': 253.0,
  },
  101: {
    'chemical_sign': 'Md',
    'name': 'Mendelévium',
    'license_number': 101,
    'relative_mass': 256.0,
  },
  102: {
    'chemical_sign': 'No',
    'name': 'Nobélium',
    'license_number': 102,
    'relative_mass': 254.0,
  },
  103: {
    'chemical_sign': 'Lr',
    'name': 'Laurencium',
    'license_number': 103,
    'relative_mass': 257.0,
  },
  104: {
    'chemical_sign': 'Rf',
    'name': 'Raderfordium',
    'license_number': 104,
    'relative_mass': 267.0,
  },
  105: {
    'chemical_sign': 'Db',
    'name': 'Dubnium',
    'license_number': 105,
    'relative_mass': 268.0,
  },
  106: {
    'chemical_sign': 'Sg',
    'name': 'Sziborgium',
    'license_number': 106,
    'relative_mass': 269.0,
  },
  107: {
    'chemical_sign': 'Bh',
    'name': 'Bohrium',
    'license_number': 107,
    'relative_mass': 270.0,
  },
  108: {
    'chemical_sign': 'Hs',
    'name': 'Hasszium',
    'license_number': 108,
    'relative_mass': 277.0,
  },
  109: {
    'chemical_sign': 'Mt',
    'name': 'Mietnerium',
    'license_number': 109,
    'relative_mass': 278.0,
  },
  110: {
    'chemical_sign': 'Ds',
    'name': 'Darstadtium',
    'license_number': 110,
    'relative_mass': 281.0,
  },
  111: {
    'chemical_sign': 'Rg',
    'name': 'Röntgénium',
    'license_number': 111,
    'relative_mass': 282.0,
  },
  112: {
    'chemical_sign': 'Cn',
    'name': 'Kopernícium',
    'license_number': 112,
    'relative_mass': 285.0,
  },
  113: {
    'chemical_sign': 'Nh',
    'name': 'Nihónium',
    'license_number': 113,
    'relative_mass': 286.0,
  },
  114: {
    'chemical_sign': 'Fl',
    'name': 'Fleróvium',
    'license_number': 114,
    'relative_mass': 289.0,
  },
  115: {
    'chemical_sign': 'Mc',
    'name': 'Moszkóvium',
    'license_number': 115,
    'relative_mass': 290.0,
  },
  116: {
    'chemical_sign': 'Lv',
    'name': 'Livermórium',
    'license_number': 116,
    'relative_mass': 293.0,
  },
  117: {
    'chemical_sign': 'Ts',
    'name': 'Tenesszium',
    'license_number': 117,
    'relative_mass': 294.0,
  },
  118: {
    'chemical_sign': 'Og',
    'name': 'Oganeszon',
    'license_number': 118,
    'relative_mass': 294.0,
  },
};
